[build]
  publish = "docs"

[[redirects]]
  from = "/privacy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms-and-conditions.html"
  status = 200

[[redirects]]
  from = "/get"
  to = "/get.html"
  status = 200

[[redirects]]
  from = "/download"
  to = "/get.html"
  status = 200
